# Python CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      #- run:
      #    name: obtain repo from GitHub
      #    command: |
      #      python3 -m venv venv
      #      . venv/bin/activate
      #      pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
            pytest -v --cov=utils
      - run:
          name: Commit to GitHub
          command: |
            if [[ "${CIRCLE_BRANCH}" = "dev" ]]
            then
              git config --global user.email "juancarlos.liebana@apara.es"
              git config --global user.name "CircleCI Job"
              git commit --allow-empty -am "Automatic commit from CircleCI [skip ci]"
              git push --set-upstream origin main
            else
              echo "No es la rama dev por lo que no hay nada que subir a git"
            fi
